services:
  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 5540:5540
    volumes:
      - redis_insight_volume_data:/db
  postgres:
      image: postgres:10.4
      restart: always
      ports:
          - "5432:5432"
      environment: 
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
  
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
      ports:
          - "8080:80"

volumes:
  redis_volume_data:
  redis_insight_volume_data: